### ISSUE TITLE
package.reload() fails in development console

### ISSUE THREAD

**Issue by ddosoff** [igorcoding/tarantool-appstarter#2]
When using development mode console:

`make run`

Calling:

`package.reload()`

Says:

> ...
>  error: 'builtin/console.lua:271: console is already started'

**Comment by igorcoding** [comment]
package.reload() executes init.lua, so when it comes to running line `console.start()` it just executes it again, and only this line says that console is already running.
So, basically package.reload() does not fail. You can just ignore this message, as in production console is not started and this message will not appear on a production server.
