### ISSUE TITLE
Typo ?

### ISSUE THREAD

**Issue by andrew-statsenko** [igorcoding/tarantool-appstarter#4]
https://github.com/igorcoding/tarantool-appstarter/blob/master/template/rpm/%7B%7B__appname__%7D%7D.spec#L10

**Comment by igorcoding** [comment]
Yeah, probably need to merge this commit
https://github.com/Mons/tarantool-appstarter/commit/fab2bbff21d421d698670d9e0e0f83bd80a2ba3c

**Comment by igorcoding** [comment]
fixed
