### ISSUE TITLE
broken rpm %install phase

### ISSUE THREAD

**Issue by andrew-statsenko** [igorcoding/tarantool-appstarter#6]
https://github.com/igorcoding/tarantool-appstarter/blob/master/template/rpm/%7B%7B__appname__%7D%7D.spec#L77

File  conf.inst.lua missed, so no way to run %install phase.

**Comment by igorcoding** [comment]
Fixed in https://github.com/igorcoding/tarantool-appstarter/commit/4a076b3583de235b740a6ff0767dff0d4c685244
